version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:C_20051685@localhost:3306//secure_file_db
      - SECRET_KEY=ash_secret_key
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: C_20051685
      POSTGRES_DB: secure_file_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
